# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on:
  push:
    branches: [github-action]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Installing the npm packages
      run: npm install
      run: npm i -g http-server @lhci/cli
      
    - name: Building Next-js project if present
      run: npm run export --if-present
      
    - name: Testing if scripts present
      run: npm test --if-present
      
    - name: nojekyll setup to solve _next static errors
      run: touch ./out/.nojekyll
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: master # The branch the action should deploy to.
        folder: out
    - name: LighthouseCI
      run: lhci autorun